package com.example.demo.controller;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.example.demo.model.Student;
import com.example.demo.repository.StudentRepository;

// This is the controller for the student. It has endpoints for getting all students and adding a new student. It uses a dynamic array list to store the students, which allows the API to add new students when it gets a request.
@RestController
// This annotation tells spring boot "This class is a controller for the API. It will handle incoming requests and send responses."
@RequestMapping("/api/students")

public class StudentController {
// Replacing the dynamic array list with a repository allows us to use the database to store the students instead of a dynamic array list in the controller. This is more efficient and allows us to persist the data even when the API is restarted.
    @Autowired
    private StudentRepository repository;
// Endpoints for the API. The GET endpoint allows the API to send a response with all the students 
    @GetMapping
    public List<Student> getAllStudents() {
        return repository.findAll(); // This uses the findAll method provided by JpaRepository to get all the students from the database and return them in the response.
    }
// The POST endpoint allows the API to add a new student when it gets a request.
    @PostMapping
    public Student addStudent(@RequestBody Student student) { // This annotation tells spring boot "This method will handle POST requests to the /api/students endpoint. The student information will be passed in the request body."
       return repository.save(student); // This uses the save method provided by JpaRepository to save the new student to the database and return the saved student in the response.
       
    }
    // The PUT endpoint allows the API to update a student when it gets a request. It takes the id of the student to update and the updated student information in the request body. It then updates the student in the list and returns the updated student.
    @PutMapping("/{id}")
    public Student updateStudent(@PathVariable int id, @RequestBody Student updatedStudent) { // This annotation tells spring boot "This method will handle PUT requests to the /api/students/{id} endpoint. The {id} in the endpoint will be passed as a parameter to the method and the updated student information will be passed in the request body."
       updatedStudent.setId(id); // This uses the setId method provided by the Student class to set the id of the updated student to the id of the student we want to update. This is necessary because the id is generated by the database and we need to make sure it matches the id of the student we want to update.
        return repository.save(updatedStudent); // This uses the save method provided by JpaRepository to save the updated student to the database and return the updated student in the response. If the student with the given id doesn't exist, it will create a new student with that id.
    }
        // The DELETE endpoint allows the API to delete a student when it gets a request. It takes the id of the student to delete in the request body. It then deletes the student from the list and returns a success message.
    @DeleteMapping("/{id}")
    public String deleteStudent(@PathVariable int id) { // This annotation tells spring boot "This method will handle DELETE requests to the /api/students/{id} endpoint. The {id} in the endpoint will be passed as a parameter to the method."
        repository.deleteById(id); // This uses the deleteById method provided by JpaRepository to delete the student with the given id from the database.
        return "Student with id " + id + " deleted successfully"; // This returns a success message in the response.
    }


}
